baseURL = "/"
languageCode = "en-us"
title = "What is a jalkin"
theme = "ananke"
SectionPagesMenu = "main"


[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  featured_image = "/images/bike_trail.jpg"
  recent_posts_number = 2
